import { mkdir, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "../../domain/config";
import {
  type CompiledCommand,
  applyOverrides,
  autoAppendArguments,
  buildFrontmatter,
  decrementPositionalArgs,
} from "../command-compiler";
import { type DiscoveredCommand, discoverCommands } from "../command-discovery";
import { checkCommandHealth } from "../command-health";
import {
  type CommandManifest,
  assertValidCommandManifest,
  readManifest,
} from "../command-manifest";
import type { CommandInstallConfig, ComponentStatus, InstallConfig } from "../types";

// Claude command skills share a directory with user-authored skills, so file
// ownership must be explicit instead of inferred from the shared command manifest.
const SHAKA_MANAGED_MARKER = "<!-- Generated by Shaka - do not edit manually -->";
const SHAKA_MANAGED_SUFFIX = `\n\n${SHAKA_MANAGED_MARKER}\n`;

export function compileClaudeCommand(
  command: DiscoveredCommand,
  targetDir: string,
): CompiledCommand {
  const fields = applyOverrides(command, "claude");
  const rawBody = autoAppendArguments(command.body);
  if (/\$0\b/.test(rawBody)) {
    console.error(
      `  ⚠ "${command.name}" uses $0 — Shaka positional args are 1-based ($1, $2, ...)`,
    );
  }
  const body = decrementPositionalArgs(rawBody);

  const frontmatter = buildFrontmatter({
    name: command.name,
    description: fields.description,
    "argument-hint": fields.argumentHint,
    model: fields.model,
    context: fields.subtask ? "fork" : undefined,
    "user-invocable": fields.userInvocable ?? true,
  });

  return {
    path: join(targetDir, command.name, "SKILL.md"),
    content: frontmatter + body + SHAKA_MANAGED_SUFFIX,
  };
}

function removeGeneratedMarker(content: string): string {
  return content.endsWith(SHAKA_MANAGED_SUFFIX)
    ? content.slice(0, -SHAKA_MANAGED_SUFFIX.length)
    : content;
}

async function isShakaManagedSkill(skillPath: string, compiledContent?: string): Promise<boolean> {
  const file = Bun.file(skillPath);
  if (!(await file.exists())) return false;

  const content = await file.text();
  return (
    content.endsWith(SHAKA_MANAGED_SUFFIX) ||
    (compiledContent !== undefined && content === removeGeneratedMarker(compiledContent))
  );
}

async function removeManagedSkill(skillsDir: string, name: string): Promise<void> {
  const skillDir = join(skillsDir, name);
  if (await isShakaManagedSkill(join(skillDir, "SKILL.md"))) {
    await rm(skillDir, { recursive: true, force: true });
  }
}

export async function installClaudeCommands(
  config: CommandInstallConfig,
  claudeHome: string,
): Promise<void> {
  const { commands, manifest } = config;
  assertValidCommandManifest(manifest);
  const globalSkillsDir = join(claudeHome, "skills");

  for (const name of manifest.global) await removeManagedSkill(globalSkillsDir, name);
  for (const [cwdPath, names] of Object.entries(manifest.scoped)) {
    for (const name of names) {
      await removeManagedSkill(join(cwdPath, ".claude", "skills"), name);
    }
  }

  for (const cmd of commands) {
    if (cmd.cwd) {
      await installScopedSkill(cmd);
    } else {
      await installGlobalSkill(cmd, globalSkillsDir);
    }
  }
}

async function installGlobalSkill(cmd: DiscoveredCommand, skillsDir: string): Promise<void> {
  const targetPath = join(skillsDir, cmd.name);
  const compiled = compileClaudeCommand(cmd, skillsDir);
  if (
    (await Bun.file(compiled.path).exists()) &&
    !(await isShakaManagedSkill(compiled.path, compiled.content))
  ) {
    console.error(
      `  ⚠ Skipped "${cmd.name}" — pre-existing skill found at ${targetPath}/\n    To let Shaka manage it, remove the existing skill first, then run shaka reload.`,
    );
    return;
  }

  await mkdir(join(skillsDir, cmd.name), { recursive: true });
  await Bun.write(compiled.path, compiled.content);
}

async function installScopedSkill(cmd: DiscoveredCommand): Promise<void> {
  for (const cwdPath of cmd.cwd ?? []) {
    const dirExists = await stat(cwdPath)
      .then((s) => s.isDirectory())
      .catch(() => false);
    if (!dirExists) {
      console.error(`  ⚠ Skipped "${cmd.name}" at ${cwdPath} — directory does not exist`);
      continue;
    }

    const skillsDir = join(cwdPath, ".claude", "skills");
    const targetPath = join(skillsDir, cmd.name);
    const compiled = compileClaudeCommand(cmd, skillsDir);

    if (
      (await Bun.file(compiled.path).exists()) &&
      !(await isShakaManagedSkill(compiled.path, compiled.content))
    ) {
      console.error(
        `  ⚠ Skipped "${cmd.name}" — pre-existing skill found at ${targetPath}/\n    To let Shaka manage it, remove the existing skill first, then run shaka reload.`,
      );
      continue;
    }

    await mkdir(join(skillsDir, cmd.name), { recursive: true });
    await Bun.write(compiled.path, compiled.content);

    console.log(`  ℹ Installed "${cmd.name}" to ${targetPath}/`);
    console.log(
      `    These are generated files. Consider adding .claude/skills/${cmd.name}/ to .gitignore`,
    );
  }
}

export async function uninstallClaudeCommands(
  config: InstallConfig,
  claudeHome: string,
): Promise<void> {
  const skillsDir = join(claudeHome, "skills");
  const manifest = await readManifest(config.shakaHome);

  for (const name of manifest.global) await removeManagedSkill(skillsDir, name);
  for (const [cwdPath, names] of Object.entries(manifest.scoped)) {
    for (const name of names) {
      await removeManagedSkill(join(cwdPath, ".claude", "skills"), name);
    }
  }
}

export async function checkClaudeCommands(
  config: InstallConfig,
  claudeHome: string,
): Promise<ComponentStatus> {
  let manifest: CommandManifest;
  try {
    manifest = await readManifest(config.shakaHome);
  } catch (e) {
    return { ok: false, issue: e instanceof Error ? e.message : String(e) };
  }
  const shakaConfig = await loadConfig(config.shakaHome);
  const { commands } = await discoverCommands(config.shakaHome, shakaConfig?.commands?.disabled);

  const isEmpty =
    commands.length === 0 &&
    manifest.global.length === 0 &&
    Object.keys(manifest.scoped).length === 0;
  if (isEmpty) return { ok: true };

  return checkCommandHealth(
    commands,
    manifest,
    ({ command, cwd }) =>
      cwd
        ? join(cwd, ".claude", "skills", command.name, "SKILL.md")
        : join(claudeHome, "skills", command.name, "SKILL.md"),
    async ({ command, cwd }, path) => {
      const skillsDir = cwd ? join(cwd, ".claude", "skills") : join(claudeHome, "skills");
      return isShakaManagedSkill(path, compileClaudeCommand(command, skillsDir).content);
    },
  );
}
