import { mkdir, readdir, unlink } from "node:fs/promises";
import { basename, join } from "node:path";
import { parse as parseYaml } from "yaml";

/** YAML frontmatter fields used for TOML translation. */
interface AgentFrontmatter {
  name: string;
  description: string;
  hidden?: boolean;
  permissions?: {
    allow?: string[];
    deny?: string[];
  };
}

/** Tools that indicate write access is needed. */
const WRITE_TOOLS = ["Write", "Edit", "MultiEdit"];
const GENERATED_MARKER = "# Generated by Shaka";

/** Parse YAML frontmatter string into a record. */
function parseFrontmatter(yamlStr: string): Record<string, unknown> {
  try {
    const parsed = parseYaml(yamlStr);
    if (parsed && typeof parsed === "object") return parsed as Record<string, unknown>;
  } catch {
    // Malformed YAML - return empty
  }
  return {};
}

/**
 * Determine sandbox_mode from permissions.
 * - allow list with write tools -> "workspace-write"
 * - deny list (no allow) -> "read-only"
 * - No permissions -> "workspace-write" (let the agent work)
 */
function determineSandboxMode(
  permissions?: AgentFrontmatter["permissions"],
): "read-only" | "workspace-write" {
  if (!permissions) return "workspace-write";

  if (permissions.allow && permissions.allow.length > 0) {
    const hasWrite = permissions.allow.some((tool) =>
      WRITE_TOOLS.some((wt) => tool === wt || tool.startsWith(`${wt}(`)),
    );
    return hasWrite ? "workspace-write" : "read-only";
  }

  if (permissions.deny && permissions.deny.length > 0) {
    return "read-only";
  }

  return "workspace-write";
}

function normalizeStringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const strings = value.filter((item): item is string => typeof item === "string");
  return strings.length > 0 ? strings : undefined;
}

function normalizePermissions(raw: unknown): AgentFrontmatter["permissions"] | undefined {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return undefined;
  const obj = raw as Record<string, unknown>;
  const allow = normalizeStringArray(obj.allow);
  const deny = normalizeStringArray(obj.deny);
  return allow || deny ? { allow, deny } : undefined;
}

function safeAgentFileStem(raw: string): string {
  const safe = raw.trim().replace(/[^a-zA-Z0-9._-]/g, "-");
  if (!safe || safe === "." || safe === "..") return "agent";
  return safe;
}

async function isGeneratedToml(path: string): Promise<boolean> {
  return Bun.file(path)
    .text()
    .then((content) => content.includes(GENERATED_MARKER))
    .catch(() => false);
}

async function generatedTomlsOutside(outputDir: string, expected: Set<string>): Promise<string[]> {
  let entries: string[];
  try {
    entries = await readdir(outputDir);
  } catch {
    return [];
  }

  const stale: string[] = [];
  for (const file of entries) {
    if (!file.endsWith(".toml") || expected.has(file)) continue;
    const path = join(outputDir, file);
    if (await isGeneratedToml(path)) stale.push(file);
  }
  return stale;
}

async function removeGeneratedTomlsOutside(
  outputDir: string,
  expected: Set<string>,
): Promise<void> {
  for (const file of await generatedTomlsOutside(outputDir, expected)) {
    await unlink(join(outputDir, file)).catch(() => {});
  }
}

/** Escape a string for TOML basic string (double-quoted). */
function escapeTomlString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Translate a Shaka agent MD file to Codex TOML format.
 * Returns null for hidden agents or files without frontmatter.
 */
export async function translateAgentToToml(
  mdPath: string,
): Promise<{ fileStem: string; name: string; toml: string } | null> {
  const content = await Bun.file(mdPath).text();

  const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!fmMatch?.[1] || !fmMatch[2]) return null;

  const parsed = parseFrontmatter(fmMatch[1]);
  const fileStem = safeAgentFileStem(basename(mdPath, ".md"));
  const parsedName = typeof parsed.name === "string" ? parsed.name.trim() : "";
  const name = parsedName || fileStem;
  const description = String(parsed.description ?? "");
  const hidden = parsed.hidden === true;

  if (hidden) return null;

  const body = fmMatch[2].trim();
  const permissions = normalizePermissions(parsed.permissions);
  const sandboxMode = determineSandboxMode(permissions);

  let instructionsBlock: string;
  if (body.includes("'''")) {
    const escapedBody = body.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
    instructionsBlock = `developer_instructions = """\n${escapedBody}\n"""`;
  } else {
    instructionsBlock = `developer_instructions = '''\n${body}\n'''`;
  }

  const toml = [
    "# Generated by Shaka — do not edit manually",
    `name = "${escapeTomlString(name)}"`,
    `description = "${escapeTomlString(description)}"`,
    `sandbox_mode = "${sandboxMode}"`,
    "",
    instructionsBlock,
    "",
  ].join("\n");

  return { fileStem, name, toml };
}

async function collectGeneratedAgentTomls(
  agentsDir: string,
): Promise<Array<{ fileName: string; toml: string }>> {
  let files: string[];
  try {
    files = await readdir(agentsDir);
  } catch {
    return [];
  }

  const generated: Array<{ fileName: string; toml: string }> = [];
  const seenFileNames = new Map<string, string>();
  for (const file of files) {
    if (!file.endsWith(".md")) continue;

    const result = await translateAgentToToml(join(agentsDir, file));
    if (!result) continue;

    const fileName = `${result.fileStem}.toml`;
    const firstSource = seenFileNames.get(fileName);
    if (firstSource) {
      throw new Error(
        `Duplicate generated Codex agent filename "${fileName}" from "${firstSource}" and "${file}"`,
      );
    }
    seenFileNames.set(fileName, file);
    generated.push({ fileName, toml: result.toml });
  }
  return generated;
}

export async function generateAgentTomls(shakaHome: string, codexHome: string): Promise<void> {
  const agentsDir = join(shakaHome, "system", "agents");
  const outputDir = join(codexHome, "agents");
  await mkdir(outputDir, { recursive: true });

  const generated = await collectGeneratedAgentTomls(agentsDir);
  await removeGeneratedTomlsOutside(outputDir, new Set(generated.map((agent) => agent.fileName)));

  for (const agent of generated) {
    await Bun.write(join(outputDir, agent.fileName), agent.toml);
  }
}

export async function removeAgentTomls(shakaHome: string, codexHome: string): Promise<void> {
  const outputDir = join(codexHome, "agents");
  await removeGeneratedTomlsOutside(outputDir, new Set());
}

export async function checkAgentTomls(
  shakaHome: string,
  codexHome: string,
): Promise<{ ok: boolean; issue?: string }> {
  const agentsDir = join(shakaHome, "system", "agents");
  const outputDir = join(codexHome, "agents");

  const missing: string[] = [];
  const generated = await collectGeneratedAgentTomls(agentsDir);
  const expected = new Set(generated.map((agent) => agent.fileName));
  for (const agent of generated) {
    const tomlPath = join(outputDir, agent.fileName);
    if (!(await Bun.file(tomlPath).exists())) {
      missing.push(agent.fileName);
    }
  }

  if (missing.length > 0) {
    return {
      ok: false,
      issue: `Missing agent TOML files: ${missing.join(", ")}`,
    };
  }

  const stale = await generatedTomlsOutside(outputDir, expected);
  if (stale.length > 0) {
    return {
      ok: false,
      issue: `stale generated agent TOML files: ${stale.join(", ")}`,
    };
  }

  return { ok: true };
}
