/**
 * Codex provider configuration.
 *
 * Codex CLI uses subprocess hooks (JSON stdin/stdout) like Claude Code.
 * Installs hooks in ~/.codex/hooks.json, generates a wrapper script for
 * context injection and subagent detection, symlinks agents and skills.
 *
 * Hooks are discovered from ${shakaHome}/system/hooks/*.ts and ${shakaHome}/customizations/hooks/*.ts
 * Each hook declares its trigger event via: TRIGGER: EventName
 */

import { mkdir, readdir, rm, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { type Result, err, ok } from "../../domain/result";
import { shellQuotePosix } from "../../platform/paths";
import {
  installAssetSymlink,
  installPerSkillSymlinks,
  uninstallAssetSymlink,
  uninstallPerSkillSymlinks,
  verifyPerSkillSymlinks,
} from "../asset-installer";
import { compileForCodex } from "../command-compiler";
import { readManifest } from "../command-manifest";
import { type DiscoveredHook, SHAKA_TO_CODEX_EVENT, discoverAllHooks } from "../hook-discovery";
import type {
  CommandInstallConfig,
  InstallConfig,
  InstallationStatus,
  ProviderConfigurer,
} from "../types";

interface CodexHookEntry {
  matcher?: string;
  hooks: Array<{
    type: "command";
    command: string;
  }>;
}

// ---------------------------------------------------------------------------
// Agent MD → TOML Translation
// ---------------------------------------------------------------------------

/** YAML frontmatter fields used for TOML translation. */
interface AgentFrontmatter {
  name: string;
  description: string;
  hidden?: boolean;
  permissions?: {
    allow?: string[];
    deny?: string[];
  };
}

/** Tools that indicate write access is needed. */
const WRITE_TOOLS = ["Write", "Edit", "MultiEdit"];

/** Parse YAML frontmatter string into a record. */
function parseFrontmatter(yamlStr: string): Record<string, unknown> {
  try {
    const parsed = parseYaml(yamlStr);
    if (parsed && typeof parsed === "object") return parsed as Record<string, unknown>;
  } catch {
    // Malformed YAML — return empty
  }
  return {};
}

/**
 * Determine sandbox_mode from permissions.
 * - allow list with write tools -> "workspace-write"
 * - deny list (no allow) -> "read-only"
 * - No permissions -> "workspace-write" (let the agent work)
 */
function determineSandboxMode(
  permissions?: AgentFrontmatter["permissions"],
): "read-only" | "workspace-write" {
  if (!permissions) return "workspace-write";

  if (permissions.allow && permissions.allow.length > 0) {
    const hasWrite = permissions.allow.some((tool) =>
      WRITE_TOOLS.some((wt) => tool === wt || tool.startsWith(`${wt}(`)),
    );
    return hasWrite ? "workspace-write" : "read-only";
  }

  if (permissions.deny && permissions.deny.length > 0) {
    return "read-only";
  }

  return "workspace-write";
}

/** Escape a string for TOML basic string (double-quoted). */
function escapeTomlString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/**
 * Translate a Shaka agent MD file to Codex TOML format.
 * Returns null for hidden agents or files without frontmatter.
 */
async function translateAgentToToml(
  mdPath: string,
): Promise<{ name: string; toml: string } | null> {
  const content = await Bun.file(mdPath).text();

  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch?.[1] || !fmMatch[2]) return null;

  const parsed = parseFrontmatter(fmMatch[1]);
  const name = String(parsed.name ?? "");
  const description = String(parsed.description ?? "");
  const hidden = parsed.hidden === true;

  if (hidden) return null;

  const body = fmMatch[2].trim();
  const permissions = parsed.permissions as AgentFrontmatter["permissions"];
  const sandboxMode = determineSandboxMode(permissions);

  // Use TOML literal strings ('''...''') — no escape interpretation,
  // safe for backslashes, regex, and code blocks in markdown.
  let instructionsBlock: string;
  if (body.includes("'''")) {
    // Rare edge case: body contains ''', fall back to basic multi-line strings
    const escapedBody = body.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');
    instructionsBlock = `developer_instructions = """\n${escapedBody}\n"""`;
  } else {
    instructionsBlock = `developer_instructions = '''\n${body}\n'''`;
  }

  const toml = [
    "# Generated by Shaka — do not edit manually",
    `name = "${escapeTomlString(name)}"`,
    `description = "${escapeTomlString(description)}"`,
    `sandbox_mode = "${sandboxMode}"`,
    "",
    instructionsBlock,
    "",
  ].join("\n");

  return { name, toml };
}

// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Hook JSON helpers
// ---------------------------------------------------------------------------

/** Group discovered hooks by their Codex event name, skipping null mappings. */
function groupHooksByCodexEvent(hooks: DiscoveredHook[]): Map<string, DiscoveredHook[]> {
  const grouped = new Map<string, DiscoveredHook[]>();
  for (const hook of hooks) {
    const codexEvent = SHAKA_TO_CODEX_EVENT[hook.event];
    if (codexEvent === null) continue;
    const existing = grouped.get(codexEvent) ?? [];
    existing.push(hook);
    grouped.set(codexEvent, existing);
  }
  return grouped;
}

// Codex `command` is shell-parsed (same as Claude). The shared
// `shellQuotePosix` defends against spaces AND `$VAR`/`$(cmd)`/backtick
// expansion via single quotes — see src/platform/paths.ts.

/** Build hooks.json entries for one Codex event. */
function buildEventEntries(
  eventHooks: DiscoveredHook[],
  codexEvent: string,
  wrapperPath: string,
): CodexHookEntry[] {
  const entries: CodexHookEntry[] = [];

  const withMatchers = eventHooks.filter((h) => h.matchers && h.matchers.length > 0);
  const withoutMatchers = eventHooks.filter((h) => !h.matchers || h.matchers.length === 0);

  // Group hooks by matcher value
  const byMatcher = new Map<string, string[]>();
  for (const hook of withMatchers) {
    for (const matcher of hook.matchers ?? []) {
      const paths = byMatcher.get(matcher) ?? [];
      paths.push(hook.path);
      byMatcher.set(matcher, paths);
    }
  }

  for (const [matcher, hookPaths] of byMatcher) {
    entries.push({
      matcher,
      hooks: hookPaths.map((p) => ({
        type: "command" as const,
        // Quote both paths so Codex's shell parser doesn't word-split on
        // spaces in $HOME (e.g. "/Users/Jane Doe/.codex/...").
        command: `bun ${shellQuotePosix(wrapperPath)} ${codexEvent} ${shellQuotePosix(p)}`,
      })),
    });
  }

  if (withoutMatchers.length > 0) {
    const entry: CodexHookEntry = {
      hooks: withoutMatchers.map((h) => ({
        type: "command" as const,
        command: `bun ${shellQuotePosix(wrapperPath)} ${codexEvent} ${shellQuotePosix(h.path)}`,
      })),
    };
    if (codexEvent === "SessionStart") {
      entry.matcher = "startup|resume";
    }
    entries.push(entry);
  }

  return entries;
}

// ---------------------------------------------------------------------------

/** Default command runner using Bun.spawn. */
async function defaultRunCommand(args: string[]): Promise<{ exitCode: number; stderr: string }> {
  const proc = Bun.spawn(args, { stdout: "pipe", stderr: "pipe" });
  const exitCode = await proc.exited;
  const stderr = await new Response(proc.stderr).text();
  return { exitCode, stderr: stderr.trim() };
}

export class CodexProviderConfigurer implements ProviderConfigurer {
  readonly name = "codex" as const;
  readonly label = "Codex";
  readonly skillsDir: string;
  private readonly codexHome: string;
  private readonly runCommand: (args: string[]) => Promise<{ exitCode: number; stderr: string }>;

  constructor(options?: {
    codexHome?: string;
    skillsDir?: string;
    runCommand?: (args: string[]) => Promise<{ exitCode: number; stderr: string }>;
  }) {
    this.codexHome = options?.codexHome ?? join(homedir(), ".codex");
    // Codex uses ~/.agents/skills/ for user-level skills
    this.skillsDir = options?.skillsDir ?? join(homedir(), ".agents", "skills");
    this.runCommand = options?.runCommand ?? defaultRunCommand;
  }

  isInstalled(): boolean {
    return Bun.which("codex") !== null;
  }

  async install(config: InstallConfig): Promise<Result<void, Error>> {
    try {
      // 1. Enable hooks feature flag
      await this.enableHooksFeature();

      // 2. Discover hooks and separate session.end for debounce
      await mkdir(this.codexHome, { recursive: true });
      const discoveredHooks = await discoverAllHooks(config.shakaHome);
      const sessionEndHooks = discoveredHooks.filter((h) => h.event === "session.end");

      // 3. Generate hook wrapper script (includes marker deletion for UserPromptSubmit)
      const wrapperPath = join(this.codexHome, "shaka-hook-wrapper.ts");
      await Bun.write(
        wrapperPath,
        this.generateWrapperContent(config.shakaHome, sessionEndHooks.length > 0),
      );

      // 4. Generate debounce scripts if session.end hooks exist
      let debouncePath: string | null = null;
      if (sessionEndHooks.length > 0) {
        debouncePath = join(this.codexHome, "shaka-session-debounce.ts");
        const workerPath = join(this.codexHome, "shaka-debounce-worker.ts");
        await Bun.write(debouncePath, this.generateDebounceContent(config.shakaHome, workerPath));
        await Bun.write(
          workerPath,
          this.generateDebounceWorkerContent(config.shakaHome, sessionEndHooks),
        );
      }

      // 5. Write hooks.json
      const hooksJson = this.generateHooksJson(discoveredHooks, wrapperPath, debouncePath);
      await Bun.write(join(this.codexHome, "hooks.json"), JSON.stringify(hooksJson, null, 2));

      // 6. Install agent symlinks (kept for backward compat)
      await installAssetSymlink(
        join(config.shakaHome, "system", "agents"),
        join(this.codexHome, "agents"),
      );

      // 7. Generate agent TOML files (Codex agents use TOML, not Markdown)
      await this.generateAgentTomls(config.shakaHome);

      // 8. Install skill symlinks (per-skill so providers discover each as a direct child)
      await installPerSkillSymlinks(join(config.shakaHome, "system", "skills"), this.skillsDir);

      // Installed third-party skills: per-skill symlinks
      await installPerSkillSymlinks(join(config.shakaHome, "skills"), this.skillsDir);

      return ok(undefined);
    } catch (e) {
      return err(e instanceof Error ? e : new Error(String(e)));
    }
  }

  /**
   * Enable the hooks feature flag.
   * Falls back to printing manual instructions if the command fails.
   */
  private async enableHooksFeature(): Promise<void> {
    try {
      const { exitCode } = await this.runCommand(["codex", "features", "enable", "hooks"]);
      if (exitCode === 0) {
        console.error("Enabled hooks feature flag in ~/.codex/config.toml");
      } else {
        console.error(
          "Could not enable hooks automatically.\n" + "Please run: codex features enable hooks",
        );
      }
    } catch {
      console.error(
        "Could not enable hooks automatically.\n" + "Please run: codex features enable hooks",
      );
    }
  }

  /**
   * Generate the hook wrapper script content.
   * The wrapper:
   * 1. Reads stdin (Codex JSON payload)
   * 2. Detects subagent sessions via missing transcript_path
   * 3. On UserPromptSubmit: deletes pending debounce marker (cancel signal)
   * 4. Spawns the child hook with SHAKA_CODEX_SUBAGENT=true if subagent
   * 5. Branches on event type for output handling:
   *    - PreToolUse/PostToolUse: pass through stdout + exit code verbatim
   *    - SessionStart/UserPromptSubmit: wrap stdout in hookSpecificOutput JSON
   * 6. Exit code 2 passthrough for ALL events (hard block)
   */
  private generateWrapperContent(shakaHome: string, hasDebounce: boolean): string {
    // Generate the marker deletion block only when debounce is active
    const markerDeletionBlock = hasDebounce
      ? `
// Cancel debounce: delete pending marker on UserPromptSubmit
if (eventName === "UserPromptSubmit" && stdinPayload.session_id) {
  const { join } = await import("node:path");
  const { unlink } = await import("node:fs/promises");
  const markerPath = join(${JSON.stringify(join(shakaHome, "memory"))}, \`.codex-pending-\${stdinPayload.session_id}.json\`);
  await unlink(markerPath).catch(() => {});
}
`
      : "";

    return `#!/usr/bin/env bun
/**
 * Shaka hook wrapper for Codex CLI.
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Usage: bun shaka-hook-wrapper.ts <eventName> <hookPath>
 *
 * Reads Codex JSON from stdin, detects subagent sessions,
 * spawns the child hook, and adapts output format per event type.
 */

const eventName = process.argv[2];
const hookPath = process.argv[3];

if (!eventName || !hookPath) {
  console.error("Usage: bun shaka-hook-wrapper.ts <eventName> <hookPath>");
  process.exit(1);
}

// Read stdin (Codex JSON payload)
const stdinText = await Bun.stdin.text();

let stdinPayload: Record<string, unknown> = {};
try {
  stdinPayload = JSON.parse(stdinText);
} catch {
  stdinPayload = {};
}

// Subagent detection: if transcript_path is absent, this is a subagent session
const isSubagent = !stdinPayload.transcript_path;

// Build child env - set SHAKA_CODEX_SUBAGENT if detected
const childEnv = isSubagent
  ? { ...process.env, SHAKA_CODEX_SUBAGENT: "true" }
  : { ...process.env };
${markerDeletionBlock}
// Spawn child hook
const child = Bun.spawn(["bun", hookPath], {
  stdin: new Blob([stdinText]),
  stdout: "pipe",
  stderr: "pipe",
  env: childEnv,
});

const [childStdout, childStderr, exitCode] = await Promise.all([
  new Response(child.stdout).text(),
  new Response(child.stderr).text(),
  child.exited,
]);

// Forward stderr passthrough in all cases
if (childStderr.trim()) {
  console.error(childStderr.trimEnd());
}

// Exit code 2 = hard block for ALL events
if (exitCode === 2) {
  if (childStdout.trim()) {
    console.log(childStdout.trimEnd());
  }
  process.exit(2);
}

// Branch on event type for output handling
if (eventName === "PreToolUse" || eventName === "PostToolUse") {
  // Pass through stdout + exit code verbatim (for security-validator blocking)
  if (childStdout.trim()) {
    console.log(childStdout.trimEnd());
  }
  process.exit(exitCode);
} else {
  // SessionStart / UserPromptSubmit: wrap stdout in hookSpecificOutput JSON
  const capturedOutput = childStdout.trim();
  if (capturedOutput) {
    const output = {
      hookSpecificOutput: {
        hookEventName: eventName,
        additionalContext: capturedOutput,
      },
    };
    console.log(JSON.stringify(output));
  }
}
`;
  }

  /**
   * Generate the debounce script content.
   * This script is registered under the Stop event in hooks.json.
   * It writes a per-session marker file and spawns a detached
   * shell-sleep + bun-wake worker.
   */
  private generateDebounceContent(shakaHome: string, workerPath: string): string {
    const memoryDir = join(shakaHome, "memory");
    return `#!/usr/bin/env bun
/**
 * Shaka session debounce for Codex CLI (Stop event).
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Reads stdin (Codex Stop event JSON), writes a per-session marker file,
 * and spawns a detached shell-sleep + bun-wake worker.
 * Returns {"continue": true} to stdout immediately.
 */

const stdinText = await Bun.stdin.text();

let payload: Record<string, unknown> = {};
try {
  payload = JSON.parse(stdinText);
} catch {
  // Malformed input — return continue and exit
  console.log(JSON.stringify({ "continue": true }));
  process.exit(0);
}

const sessionId = payload.session_id as string;
const transcriptPath = payload.transcript_path as string;
const cwd = payload.cwd as string;

if (!sessionId) {
  console.log(JSON.stringify({ "continue": true }));
  process.exit(0);
}

const { join } = await import("node:path");
const { mkdir } = await import("node:fs/promises");

const memoryDir = ${JSON.stringify(memoryDir)};
await mkdir(memoryDir, { recursive: true });

const timestamp = Date.now();
const markerPath = join(memoryDir, \`.codex-pending-\${sessionId}.json\`);
const marker = {
  timestamp,
  session_id: sessionId,
  transcript_path: transcriptPath,
  cwd,
};

await Bun.write(markerPath, JSON.stringify(marker));

// Spawn detached shell-sleep + bun-wake worker.
// Shell sleep uses ~500KB RSS vs Bun's ~30MB — Bun only starts after the delay.
const workerPath = ${JSON.stringify(workerPath)};
// Pass paths as positional args ($1/$2/$3) instead of interpolating into
// the shell string — keeps shell-active syntax inside any path inert.
const proc = Bun.spawn(
  ["sh", "-c", 'sleep 30 && exec bun "$1" "$2" "$3"', "sh", workerPath, markerPath, String(timestamp)],
  { stdin: "ignore", stdout: "ignore", stderr: "ignore" },
);
proc.unref();

console.log(JSON.stringify({ "continue": true }));
`;
  }

  /**
   * Generate the debounce worker script content.
   * This script is spawned by the debounce script after a 30-second sleep.
   * It checks the marker file, and if valid, fires session-end hooks via
   * the session-end.ts dispatch/worker pattern.
   */
  private generateDebounceWorkerContent(
    shakaHome: string,
    sessionEndHooks: DiscoveredHook[],
  ): string {
    const memoryDir = join(shakaHome, "memory");
    // Find the session-end.ts hook path — the first session.end hook is the primary one
    const sessionEndHookPaths = sessionEndHooks.map((h) => h.path);
    return `#!/usr/bin/env bun
/**
 * Shaka debounce worker for Codex CLI.
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Spawned by shaka-session-debounce.ts after 30s sleep.
 * Checks marker validity, then fires session-end hooks.
 */

import { mkdir, unlink } from "node:fs/promises";
import { join } from "node:path";

const markerPath = process.argv[2];
const expectedTimestamp = process.argv[3];

if (!markerPath || !expectedTimestamp) {
  process.exit(0);
}

// Check if marker still exists (UserPromptSubmit may have deleted it)
const markerFile = Bun.file(markerPath);
if (!(await markerFile.exists())) {
  // User continued — debounce cancelled
  process.exit(0);
}

// Read and validate marker JSON
let marker: { timestamp: number; session_id: string; transcript_path: string; cwd: string };
try {
  marker = await markerFile.json();
} catch {
  // Corrupted marker — delete and exit
  await unlink(markerPath).catch(() => {});
  process.exit(0);
}

// Check timestamp matches — if changed, a newer Stop event took over
if (String(marker.timestamp) !== expectedTimestamp) {
  process.exit(0);
}

// Marker is valid — fire session-end hooks
const memoryDir = ${JSON.stringify(memoryDir)};
await mkdir(memoryDir, { recursive: true });

const sessionEndInput = {
  session_id: marker.session_id,
  transcript_path: marker.transcript_path,
  cwd: marker.cwd,
  provider: "codex",
};
// Spawn a session-end worker per hook, each with its own temp file
const sessionEndHookPaths = ${JSON.stringify(sessionEndHookPaths)};
const payload = JSON.stringify(sessionEndInput);
for (const hookPath of sessionEndHookPaths) {
  const hookName = hookPath.split("/").pop()?.replace(/\\.ts$/, "") ?? "hook";
  const hookTmpPath = join(memoryDir,
    \`.session-end-input-\${marker.session_id.slice(0, 8)}-\${hookName}-\${process.pid}.json\`);
  await Bun.write(hookTmpPath, payload);
  const logPath = join(memoryDir, ".session-end-worker.log");
  const proc = Bun.spawn(["bun", hookPath, "--worker", hookTmpPath], {
    stdin: "ignore",
    stdout: "ignore",
    stderr: Bun.file(logPath),
  });
  proc.unref();
}

// Delete the marker — session-end pipeline has been triggered
await unlink(markerPath).catch(() => {});
`;
  }

  /**
   * Generate hooks.json content from discovered hooks.
   * Maps Shaka events to Codex events, skipping null mappings (session.end).
   * Groups hooks by Codex event name, using matchers for tool hooks.
   * Optionally registers the debounce script under the Stop event.
   */
  private generateHooksJson(
    hooks: DiscoveredHook[],
    wrapperPath: string,
    debouncePath?: string | null,
  ): { hooks: Record<string, CodexHookEntry[]> } {
    const codexHooks: Record<string, CodexHookEntry[]> = {};

    const hooksByCodexEvent = groupHooksByCodexEvent(hooks);

    for (const [codexEvent, eventHooks] of hooksByCodexEvent) {
      const entries = buildEventEntries(eventHooks, codexEvent, wrapperPath);
      if (entries.length > 0) {
        codexHooks[codexEvent] = entries;
      }
    }

    // Register debounce script under Stop event (after normal hook discovery)
    if (debouncePath) {
      codexHooks.Stop = [
        {
          hooks: [
            {
              type: "command" as const,
              command: `bun ${shellQuotePosix(debouncePath)}`,
            },
          ],
        },
      ];
    }

    return { hooks: codexHooks };
  }

  /** Install commands as Codex skills to the provider's skillsDir. */
  async installCommands(config: CommandInstallConfig): Promise<void> {
    const { commands, manifest } = config;

    // Clean previous installations
    for (const name of manifest.global) {
      await rm(join(this.skillsDir, name), { recursive: true, force: true });
    }

    for (const cmd of commands) {
      // Codex has no scoped commands — all commands are global skills
      if (cmd.cwd) continue;

      const compiled = compileForCodex(cmd, this.skillsDir);
      await mkdir(join(this.skillsDir, cmd.name), { recursive: true });
      await Bun.write(compiled.path, compiled.content);
      console.error(`  ℹ Installed "${cmd.name}" to ${compiled.path}`);
    }
  }

  private async uninstallCommands(config: InstallConfig): Promise<void> {
    const manifest = await readManifest(config.shakaHome);
    for (const name of manifest.global) {
      await rm(join(this.skillsDir, name), { recursive: true, force: true });
    }
  }

  async uninstall(config: InstallConfig): Promise<Result<void, Error>> {
    try {
      // Remove hooks.json
      const hooksPath = join(this.codexHome, "hooks.json");
      await this.removeShakaHooks(hooksPath);

      // Remove wrapper script
      const wrapperPath = join(this.codexHome, "shaka-hook-wrapper.ts");
      if (await Bun.file(wrapperPath).exists()) {
        await unlink(wrapperPath);
      }

      // Remove debounce scripts
      const debouncePath = join(this.codexHome, "shaka-session-debounce.ts");
      if (await Bun.file(debouncePath).exists()) {
        await unlink(debouncePath);
      }
      const debounceWorkerPath = join(this.codexHome, "shaka-debounce-worker.ts");
      if (await Bun.file(debounceWorkerPath).exists()) {
        await unlink(debounceWorkerPath);
      }

      // Remove agent symlinks
      await uninstallAssetSymlink(
        join(config.shakaHome, "system", "agents"),
        join(this.codexHome, "agents"),
      );

      // Remove generated agent TOML files (only those matching source agents)
      await this.removeAgentTomls(config.shakaHome);

      // Remove compiled command skills (installed to skillsDir by installCommands)
      await this.uninstallCommands(config);

      // Remove system skill symlinks
      await uninstallPerSkillSymlinks(join(config.shakaHome, "system", "skills"), this.skillsDir);

      // Remove installed third-party skill symlinks
      await uninstallPerSkillSymlinks(join(config.shakaHome, "skills"), this.skillsDir);

      return ok(undefined);
    } catch (e) {
      return err(e instanceof Error ? e : new Error(String(e)));
    }
  }

  async checkInstallation(config: InstallConfig): Promise<InstallationStatus> {
    const hooks = await this.checkHooks();
    // Agent check: verify TOML files exist for non-hidden agents
    const agents = await this.checkAgentTomls(config.shakaHome);
    const skills = await verifyPerSkillSymlinks(
      join(config.shakaHome, "system", "skills"),
      this.skillsDir,
      "system skills",
    );
    const installedSkills = await verifyPerSkillSymlinks(
      join(config.shakaHome, "skills"),
      this.skillsDir,
      "installed skills",
    );
    // Commands check deferred — installCommands works but per-command verification not needed
    const commands = { ok: true };

    return { hooks, agents, skills, installedSkills, commands };
  }

  /**
   * Remove Shaka-managed hooks from hooks.json, preserving user-added hooks.
   * Shaka hooks are identified by their command containing "shaka" in the path.
   * If only Shaka hooks existed, the file is deleted entirely.
   */
  private async removeShakaHooks(hooksPath: string): Promise<void> {
    const file = Bun.file(hooksPath);
    if (!(await file.exists())) return;

    let config: { hooks: Record<string, unknown[]> };
    try {
      config = (await file.json()) as typeof config;
    } catch {
      await unlink(hooksPath);
      return;
    }

    if (!config.hooks) {
      await unlink(hooksPath);
      return;
    }

    // Filter each event's hook list, keeping only non-shaka entries
    const cleaned: Record<string, unknown[]> = {};
    for (const [event, entries] of Object.entries(config.hooks)) {
      const kept = (entries as Array<{ hooks?: Array<{ command?: string }> }>).filter((entry) => {
        const commands = entry.hooks ?? [];
        // Shaka hooks reference the wrapper or debounce scripts in ~/.codex/
        return !commands.some(
          (h) =>
            h.command?.includes("shaka-hook-wrapper") ||
            h.command?.includes("shaka-session-debounce"),
        );
      });
      if (kept.length > 0) {
        cleaned[event] = kept;
      }
    }

    if (Object.keys(cleaned).length === 0) {
      await unlink(hooksPath);
    } else {
      await Bun.write(hooksPath, JSON.stringify({ hooks: cleaned }, null, 2));
    }
  }

  private async checkHooks(): Promise<{ ok: boolean; issue?: string }> {
    // Check hooks.json exists and is valid
    const hooksPath = join(this.codexHome, "hooks.json");
    const hooksFile = Bun.file(hooksPath);

    if (!(await hooksFile.exists())) {
      return { ok: false, issue: "hooks.json not found" };
    }

    try {
      const hooksJson = (await hooksFile.json()) as Record<string, unknown>;
      if (!hooksJson.hooks || typeof hooksJson.hooks !== "object") {
        return { ok: false, issue: "hooks.json missing hooks key" };
      }
    } catch {
      return { ok: false, issue: "Failed to parse hooks.json" };
    }

    // Check wrapper script exists
    const wrapperPath = join(this.codexHome, "shaka-hook-wrapper.ts");
    if (!(await Bun.file(wrapperPath).exists())) {
      return { ok: false, issue: "shaka-hook-wrapper.ts not found" };
    }

    return { ok: true };
  }

  /**
   * Generate TOML agent files from Shaka agent MD sources.
   * Translates YAML frontmatter + Markdown body to Codex TOML format.
   * Skips agents with `hidden: true` (e.g., the inference agent).
   */
  private async generateAgentTomls(shakaHome: string): Promise<void> {
    const agentsDir = join(shakaHome, "system", "agents");
    const outputDir = join(this.codexHome, "agents");
    await mkdir(outputDir, { recursive: true });

    let files: string[];
    try {
      files = await readdir(agentsDir);
    } catch {
      return; // No agents directory — nothing to do
    }

    for (const file of files) {
      if (!file.endsWith(".md")) continue;

      const result = await translateAgentToToml(join(agentsDir, file));
      if (!result) continue; // Hidden or no frontmatter

      await Bun.write(join(outputDir, `${result.name}.toml`), result.toml);
    }
  }

  /**
   * Remove generated TOML agent files.
   * Only removes files that match agent names from system/agents/ sources.
   * User-created TOML files are preserved.
   */
  private async removeAgentTomls(shakaHome: string): Promise<void> {
    const agentsDir = join(shakaHome, "system", "agents");
    const outputDir = join(this.codexHome, "agents");

    let sourceFiles: string[];
    try {
      sourceFiles = await readdir(agentsDir);
    } catch {
      return; // No source agents — nothing to remove
    }

    for (const file of sourceFiles) {
      if (!file.endsWith(".md")) continue;
      const name = file.replace(/\.md$/, "");
      // Also need to check the frontmatter name for proper matching
      const content = await Bun.file(join(agentsDir, file))
        .text()
        .catch(() => "");
      const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (fmMatch?.[1]) {
        const parsed = parseFrontmatter(fmMatch[1]);
        const agentName = String(parsed.name ?? name);
        const tomlPath = join(outputDir, `${agentName}.toml`);
        if (await Bun.file(tomlPath).exists()) {
          await unlink(tomlPath).catch(() => {});
        }
      }
    }
  }

  /**
   * Check that TOML agent files exist for all non-hidden agents.
   */
  private async checkAgentTomls(shakaHome: string): Promise<{ ok: boolean; issue?: string }> {
    const agentsDir = join(shakaHome, "system", "agents");
    const outputDir = join(this.codexHome, "agents");

    let sourceFiles: string[];
    try {
      sourceFiles = await readdir(agentsDir);
    } catch {
      return { ok: true }; // No source agents — nothing to check
    }

    const missing: string[] = [];
    for (const file of sourceFiles) {
      if (!file.endsWith(".md")) continue;

      const content = await Bun.file(join(agentsDir, file))
        .text()
        .catch(() => "");
      const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (!fmMatch?.[1]) continue;

      const parsed = parseFrontmatter(fmMatch[1]);
      if (parsed.hidden === true) continue;

      const agentName = String(parsed.name ?? file.replace(/\.md$/, ""));
      const tomlPath = join(outputDir, `${agentName}.toml`);
      if (!(await Bun.file(tomlPath).exists())) {
        missing.push(agentName);
      }
    }

    if (missing.length > 0) {
      return {
        ok: false,
        issue: `Missing agent TOML files: ${missing.join(", ")}`,
      };
    }

    return { ok: true };
  }

  /**
   * Register the Shaka MCP server with Codex.
   * Uses `codex mcp add` for correct config format.
   * Idempotent — re-adding the same name overwrites the existing entry.
   */
  async registerMcpServer(): Promise<Result<void, Error>> {
    try {
      const { exitCode, stderr } = await this.runCommand([
        "codex",
        "mcp",
        "add",
        "shaka",
        "--",
        "shaka",
        "mcp",
        "serve",
      ]);
      if (exitCode !== 0) {
        return err(new Error(`codex mcp add failed (exit ${exitCode}): ${stderr}`));
      }
      return ok(undefined);
    } catch (e) {
      return err(
        new Error(`Failed to register MCP server: ${e instanceof Error ? e.message : String(e)}`),
      );
    }
  }

  /**
   * Unregister the Shaka MCP server from Codex.
   */
  async unregisterMcpServer(): Promise<Result<void, Error>> {
    try {
      const { exitCode, stderr } = await this.runCommand(["codex", "mcp", "remove", "shaka"]);
      // Exit code non-zero is OK if server doesn't exist
      if (exitCode !== 0 && !stderr.includes("not found")) {
        return err(new Error(`codex mcp remove failed (exit ${exitCode}): ${stderr}`));
      }
      return ok(undefined);
    } catch (e) {
      return err(
        new Error(`Failed to unregister MCP server: ${e instanceof Error ? e.message : String(e)}`),
      );
    }
  }
}
