import { join } from "node:path";
import { shellQuotePosix } from "../../platform/paths";
import { type DiscoveredHook, SHAKA_TO_CODEX_EVENT } from "../hook-discovery";

interface CodexHookEntry {
  matcher?: string;
  hooks: Array<{
    type: "command";
    command: string;
  }>;
}

const SAFE_SESSION_FILE_PART_HELPER = `
function safeSessionFilePart(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  return trimmed ? encodeURIComponent(trimmed) : null;
}
`;

const SAFE_SESSION_MARKER_HELPERS = `${SAFE_SESSION_FILE_PART_HELPER}
function safeSessionMarkerPath(memoryDir: string, raw: unknown): string | null {
  const part = safeSessionFilePart(raw);
  return part ? join(memoryDir, \`.codex-pending-\${part}.json\`) : null;
}
`;

const CODEX_SESSION_END_DEBOUNCE_MS = 30_000;

/** Group discovered hooks by their Codex event name, skipping null mappings. */
function groupHooksByCodexEvent(hooks: DiscoveredHook[]): Map<string, DiscoveredHook[]> {
  const grouped = new Map<string, DiscoveredHook[]>();
  for (const hook of hooks) {
    const codexEvent = SHAKA_TO_CODEX_EVENT[hook.event];
    if (codexEvent === null) continue;
    const existing = grouped.get(codexEvent) ?? [];
    existing.push(hook);
    grouped.set(codexEvent, existing);
  }
  return grouped;
}

function buildEventEntries(
  eventHooks: DiscoveredHook[],
  codexEvent: string,
  wrapperPath: string,
): CodexHookEntry[] {
  const entries: CodexHookEntry[] = [];

  const withMatchers = eventHooks.filter((h) => h.matchers && h.matchers.length > 0);
  const withoutMatchers = eventHooks.filter((h) => !h.matchers || h.matchers.length === 0);

  const byMatcher = new Map<string, Set<string>>();
  for (const hook of withMatchers) {
    for (const matcher of hook.matchers ?? []) {
      const codexMatcher =
        codexEvent === "PreToolUse" || codexEvent === "PostToolUse"
          ? normalizeCodexToolMatcher(matcher)
          : matcher;
      const paths = byMatcher.get(codexMatcher) ?? new Set<string>();
      paths.add(hook.path);
      byMatcher.set(codexMatcher, paths);
    }
  }

  for (const [matcher, hookPaths] of byMatcher) {
    entries.push({
      matcher,
      hooks: [...hookPaths].map((p) => ({
        type: "command" as const,
        command: `bun ${shellQuotePosix(wrapperPath)} ${codexEvent} ${shellQuotePosix(p)}`,
      })),
    });
  }

  if (withoutMatchers.length > 0) {
    const entry: CodexHookEntry = {
      hooks: withoutMatchers.map((h) => ({
        type: "command" as const,
        command: `bun ${shellQuotePosix(wrapperPath)} ${codexEvent} ${shellQuotePosix(h.path)}`,
      })),
    };
    if (codexEvent === "SessionStart") {
      entry.matcher = "startup|resume";
    }
    entries.push(entry);
  }

  return entries;
}

function normalizeCodexToolMatcher(matcher: string): string {
  switch (matcher) {
    case "Edit":
    case "MultiEdit":
    case "Write":
      return "apply_patch";
    default:
      return matcher;
  }
}

export function renderCodexWrapper(shakaHome: string, hasDebounce: boolean): string {
  const markerDeletionBlock = hasDebounce
    ? `
// Cancel debounce: delete pending marker on UserPromptSubmit
if (eventName === "UserPromptSubmit" && stdinPayload.session_id) {
  const { join } = await import("node:path");
  const { unlink } = await import("node:fs/promises");
${SAFE_SESSION_MARKER_HELPERS}
  const markerPath = safeSessionMarkerPath(${JSON.stringify(join(shakaHome, "memory"))}, stdinPayload.session_id);
  if (markerPath) await unlink(markerPath).catch(() => {});
}
`
    : "";

  return `#!/usr/bin/env bun
/**
 * Shaka hook wrapper for Codex CLI.
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Usage: bun shaka-hook-wrapper.ts <eventName> <hookPath>
 *
 * Reads Codex JSON from stdin, detects subagent sessions,
 * spawns the child hook, and adapts output format per event type.
 */

const eventName = process.argv[2];
const hookPath = process.argv[3];

if (!eventName || !hookPath) {
  console.error("Usage: bun shaka-hook-wrapper.ts <eventName> <hookPath>");
  process.exit(1);
}

// Read stdin (Codex JSON payload)
const stdinText = await Bun.stdin.text();

let stdinPayload: Record<string, unknown> = {};
try {
  stdinPayload = JSON.parse(stdinText);
} catch {
  stdinPayload = {};
}

// Subagent detection: if transcript_path is absent, this is a subagent session
const isSubagent = !stdinPayload.transcript_path;

// Build child env - set SHAKA_CODEX_SUBAGENT if detected
const childEnv = isSubagent
  ? { ...process.env, SHAKA_CODEX_SUBAGENT: "true" }
  : { ...process.env };
${markerDeletionBlock}
// Spawn child hook
const child = Bun.spawn(["bun", hookPath], {
  stdin: new Blob([stdinText]),
  stdout: "pipe",
  stderr: "pipe",
  env: childEnv,
});

const [childStdout, childStderr, exitCode] = await Promise.all([
  new Response(child.stdout).text(),
  new Response(child.stderr).text(),
  child.exited,
]);

function adaptPreToolUseOutput(output: string): string {
  const trimmed = output.trim();
  if (!trimmed) return "";

  try {
    const parsed = JSON.parse(trimmed) as Record<string, unknown>;
    if (parsed.decision === "ask" && typeof parsed.message === "string") {
      return JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason:
            "Shaka requires confirmation for this operation, but Codex PreToolUse cannot request it. " +
            "Run the operation manually after review.\\n\\n" +
            parsed.message,
        },
      });
    }
  } catch {
    // Preserve non-JSON output so Codex can report the hook's actual response.
  }

  return trimmed;
}

// Forward stderr passthrough in all cases
if (childStderr.trim()) {
  console.error(childStderr.trimEnd());
}

// Exit code 2 = hard block for ALL events
if (exitCode === 2) {
  if (childStdout.trim()) {
    console.log(childStdout.trimEnd());
  }
  process.exit(2);
}

// Branch on event type for output handling
if (eventName === "PreToolUse") {
  const output = adaptPreToolUseOutput(childStdout);
  if (output) {
    console.log(output);
  }
  process.exit(exitCode);
} else if (eventName === "PostToolUse") {
  if (childStdout.trim()) {
    console.log(childStdout.trimEnd());
  }
  process.exit(exitCode);
} else {
  // SessionStart / UserPromptSubmit: wrap stdout in hookSpecificOutput JSON
  const capturedOutput = childStdout.trim();
  if (capturedOutput) {
    const output = {
      hookSpecificOutput: {
        hookEventName: eventName,
        additionalContext: capturedOutput,
      },
    };
    console.log(JSON.stringify(output));
  }
}
`;
}

export function renderCodexDebounce(shakaHome: string, workerPath: string): string {
  const memoryDir = join(shakaHome, "memory");
  return `#!/usr/bin/env bun
/**
 * Shaka session debounce for Codex CLI (Stop event).
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Reads stdin (Codex Stop event JSON), writes a per-session marker file,
 * and spawns a detached Bun worker that waits before firing hooks.
 * Returns {"continue": true} to stdout immediately.
 */

const stdinText = await Bun.stdin.text();

let payload: Record<string, unknown> = {};
try {
  payload = JSON.parse(stdinText);
} catch {
  // Malformed input — return continue and exit
  console.log(JSON.stringify({ "continue": true }));
  process.exit(0);
}

const sessionId = payload.session_id as string;
const transcriptPath = payload.transcript_path as string;
const cwd = payload.cwd as string;

if (!sessionId) {
  console.log(JSON.stringify({ "continue": true }));
  process.exit(0);
}

const { join } = await import("node:path");
const { mkdir } = await import("node:fs/promises");

const memoryDir = ${JSON.stringify(memoryDir)};
await mkdir(memoryDir, { recursive: true });

${SAFE_SESSION_MARKER_HELPERS}

const timestamp = Date.now();
const markerPath = safeSessionMarkerPath(memoryDir, sessionId);
if (!markerPath) {
  console.log(JSON.stringify({ "continue": true }));
  process.exit(0);
}
const marker = {
  timestamp,
  session_id: sessionId,
  transcript_path: transcriptPath,
  cwd,
};

await Bun.write(markerPath, JSON.stringify(marker));

// Spawn detached Bun worker. The worker owns the delay so this script can
// return immediately to Codex without depending on POSIX shell utilities.
const workerPath = ${JSON.stringify(workerPath)};
const debounceMs = ${CODEX_SESSION_END_DEBOUNCE_MS};
const proc = Bun.spawn(["bun", workerPath, markerPath, String(timestamp), String(debounceMs)], {
  stdin: "ignore",
  stdout: "ignore",
  stderr: "ignore",
});
proc.unref();

console.log(JSON.stringify({ "continue": true }));
`;
}

export function renderCodexDebounceWorker(
  shakaHome: string,
  sessionEndHooks: DiscoveredHook[],
): string {
  const memoryDir = join(shakaHome, "memory");
  const sessionEndHookPaths = sessionEndHooks.map((h) => h.path);
  return `#!/usr/bin/env bun
/**
 * Shaka debounce worker for Codex CLI.
 * Auto-generated by CodexProviderConfigurer - do not edit manually.
 *
 * Spawned by shaka-session-debounce.ts to wait, then fire hooks.
 * Checks marker validity, then fires session-end hooks.
 */

import { mkdir, unlink } from "node:fs/promises";
import { basename, join } from "node:path";

const markerPath = process.argv[2];
const expectedTimestamp = process.argv[3];
const delayMs = Number(process.argv[4]);

if (!markerPath || !expectedTimestamp || !Number.isFinite(delayMs) || delayMs < 0) {
  process.exit(0);
}

await Bun.sleep(delayMs);

// Check if marker still exists (UserPromptSubmit may have deleted it)
const markerFile = Bun.file(markerPath);
if (!(await markerFile.exists())) {
  // User continued — debounce cancelled
  process.exit(0);
}

// Read and validate marker JSON
let marker: { timestamp: number; session_id: string; transcript_path: string; cwd: string };
try {
  marker = await markerFile.json();
} catch {
  // Corrupted marker — delete and exit
  await unlink(markerPath).catch(() => {});
  process.exit(0);
}

// Check timestamp matches — if changed, a newer Stop event took over
if (String(marker.timestamp) !== expectedTimestamp) {
  process.exit(0);
}

// Marker is valid — fire session-end hooks
const memoryDir = ${JSON.stringify(memoryDir)};
await mkdir(memoryDir, { recursive: true });

const sessionEndInput = {
  session_id: marker.session_id,
  transcript_path: marker.transcript_path,
  cwd: marker.cwd,
  provider: "codex",
};
// Spawn a session-end worker per hook, each with its own temp file
const sessionEndHookPaths = ${JSON.stringify(sessionEndHookPaths)};
const payload = JSON.stringify(sessionEndInput);
${SAFE_SESSION_FILE_PART_HELPER}
for (const hookPath of sessionEndHookPaths) {
  const hookName = basename(hookPath).replace(/\\.ts$/, "") || "hook";
  const sessionFilePart = safeSessionFilePart(marker.session_id) ?? "session";
  const hookTmpPath = join(memoryDir,
    \`.session-end-input-\${sessionFilePart.slice(0, 24)}-\${hookName}-\${process.pid}.json\`);
  await Bun.write(hookTmpPath, payload);
  const logPath = join(memoryDir, ".session-end-worker.log");
  const proc = Bun.spawn(["bun", hookPath, "--worker", hookTmpPath], {
    stdin: "ignore",
    stdout: "ignore",
    stderr: Bun.file(logPath),
  });
  proc.unref();
}

// Delete the marker — session-end pipeline has been triggered
await unlink(markerPath).catch(() => {});
`;
}

export function renderCodexHooksJson(
  hooks: DiscoveredHook[],
  wrapperPath: string,
  debouncePath?: string | null,
): { hooks: Record<string, CodexHookEntry[]> } {
  const codexHooks: Record<string, CodexHookEntry[]> = {};

  const hooksByCodexEvent = groupHooksByCodexEvent(hooks);

  for (const [codexEvent, eventHooks] of hooksByCodexEvent) {
    const entries = buildEventEntries(eventHooks, codexEvent, wrapperPath);
    if (entries.length > 0) {
      codexHooks[codexEvent] = entries;
    }
  }

  if (debouncePath) {
    codexHooks.Stop = [
      {
        hooks: [
          {
            type: "command" as const,
            command: `bun ${shellQuotePosix(debouncePath)}`,
          },
        ],
      },
    ];
  }

  return { hooks: codexHooks };
}
