import { mkdir, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "../../domain/config";
import {
  type CompiledCommand,
  applyOverrides,
  autoAppendArguments,
  buildFrontmatter,
} from "../command-compiler";
import { type DiscoveredCommand, discoverCommands } from "../command-discovery";
import { checkCommandHealth } from "../command-health";
import type { CommandManifest } from "../command-manifest";
import { assertValidCommandManifest, readManifest } from "../command-manifest";
import type { CommandInstallConfig, InstallConfig } from "../types";

// OpenCode command files live next to user-authored commands, so ownership
// must be recorded in the file itself. The shared manifest says what Shaka
// discovered; the marker says which concrete files Shaka may overwrite/remove.
const OPENCODE_MANAGED_MARKER = "<!-- Generated by Shaka - do not edit manually -->";
const OPENCODE_MANAGED_SUFFIX = `\n\n${OPENCODE_MANAGED_MARKER}\n`;

export function compileOpencodeCommand(
  command: DiscoveredCommand,
  targetDir: string,
): CompiledCommand {
  const fields = applyOverrides(command, "opencode");
  const body = autoAppendArguments(command.body);

  const frontmatter = buildFrontmatter({
    description: fields.description,
    model: fields.model,
    subtask: fields.subtask,
  });

  return {
    path: join(targetDir, `${command.name}.md`),
    content: frontmatter + body + OPENCODE_MANAGED_SUFFIX,
  };
}

function removeGeneratedMarker(content: string): string {
  return content.endsWith(OPENCODE_MANAGED_SUFFIX)
    ? content.slice(0, -OPENCODE_MANAGED_SUFFIX.length)
    : content;
}

async function isShakaManagedCommand(
  commandPath: string,
  compiledContent?: string,
): Promise<boolean> {
  const file = Bun.file(commandPath);
  if (!(await file.exists())) return false;

  const content = await file.text();
  return (
    content.endsWith(OPENCODE_MANAGED_SUFFIX) ||
    (compiledContent !== undefined && content === removeGeneratedMarker(compiledContent))
  );
}

async function removeManagedCommand(commandPath: string, compiledContent?: string): Promise<void> {
  if (await isShakaManagedCommand(commandPath, compiledContent)) {
    await rm(commandPath, { force: true });
  }
}

async function discoverCompiledCommandContent(
  config: InstallConfig,
  opencodeConfigDir: string,
): Promise<Map<string, string>> {
  const shakaConfig = await loadConfig(config.shakaHome);
  const { commands } = await discoverCommands(config.shakaHome, shakaConfig?.commands?.disabled);
  const compiled = new Map<string, string>();

  for (const command of commands) {
    if (command.cwd?.length) {
      for (const cwd of command.cwd) {
        const commandsDir = join(cwd, ".opencode", "commands");
        const commandFile = compileOpencodeCommand(command, commandsDir);
        compiled.set(commandFile.path, commandFile.content);
      }
      continue;
    }
    const commandFile = compileOpencodeCommand(command, join(opencodeConfigDir, "commands"));
    compiled.set(commandFile.path, commandFile.content);
  }

  return compiled;
}

export async function installOpencodeCommands(
  config: CommandInstallConfig,
  opencodeConfigDir: string,
): Promise<void> {
  const { commands, manifest } = config;
  assertValidCommandManifest(manifest);
  const globalCommandsDir = join(opencodeConfigDir, "commands");
  await mkdir(globalCommandsDir, { recursive: true });

  for (const name of manifest.global) {
    await removeManagedCommand(join(globalCommandsDir, `${name}.md`));
  }
  for (const [cwdPath, names] of Object.entries(manifest.scoped)) {
    for (const name of names) {
      await removeManagedCommand(join(cwdPath, ".opencode", "commands", `${name}.md`));
    }
  }

  for (const cmd of commands) {
    if (cmd.cwd) {
      await installScopedCommand(cmd);
    } else {
      await installGlobalCommand(cmd, globalCommandsDir);
    }
  }
}

async function installGlobalCommand(cmd: DiscoveredCommand, commandsDir: string): Promise<void> {
  const compiled = compileOpencodeCommand(cmd, commandsDir);
  if (
    (await Bun.file(compiled.path).exists()) &&
    !(await isShakaManagedCommand(compiled.path, compiled.content))
  ) {
    console.error(
      `  ⚠ Skipped "${cmd.name}" — pre-existing command found at ${compiled.path}\n    To let Shaka manage it, remove the existing command first, then run shaka reload.`,
    );
    return;
  }

  await Bun.write(compiled.path, compiled.content);
}

async function installScopedCommand(cmd: DiscoveredCommand): Promise<void> {
  for (const cwdPath of cmd.cwd ?? []) {
    const dirExists = await stat(cwdPath)
      .then((s) => s.isDirectory())
      .catch(() => false);
    if (!dirExists) {
      console.error(`  ⚠ Skipped "${cmd.name}" at ${cwdPath} — directory does not exist`);
      continue;
    }

    const commandsDir = join(cwdPath, ".opencode", "commands");
    const targetPath = join(commandsDir, `${cmd.name}.md`);
    const compiled = compileOpencodeCommand(cmd, commandsDir);

    if (
      (await Bun.file(compiled.path).exists()) &&
      !(await isShakaManagedCommand(compiled.path, compiled.content))
    ) {
      console.error(
        `  ⚠ Skipped "${cmd.name}" — pre-existing command found at ${targetPath}\n    To let Shaka manage it, remove the existing command first, then run shaka reload.`,
      );
      continue;
    }

    await mkdir(commandsDir, { recursive: true });
    await Bun.write(compiled.path, compiled.content);

    console.log(`  ℹ Installed "${cmd.name}" to ${targetPath}`);
    console.log(
      `    These are generated files. Consider adding .opencode/commands/${cmd.name}.md to .gitignore`,
    );
  }
}

export async function uninstallOpencodeCommands(
  config: InstallConfig,
  opencodeConfigDir: string,
): Promise<void> {
  const commandsDir = join(opencodeConfigDir, "commands");
  const manifest = await readManifest(config.shakaHome);
  const compiledContent = await discoverCompiledCommandContent(config, opencodeConfigDir);

  for (const name of manifest.global) {
    const commandPath = join(commandsDir, `${name}.md`);
    await removeManagedCommand(commandPath, compiledContent.get(commandPath));
  }
  for (const [cwdPath, names] of Object.entries(manifest.scoped)) {
    for (const name of names) {
      const commandPath = join(cwdPath, ".opencode", "commands", `${name}.md`);
      await removeManagedCommand(commandPath, compiledContent.get(commandPath));
    }
  }
}

export async function checkOpencodeCommands(
  config: InstallConfig,
  opencodeConfigDir: string,
): Promise<{ ok: boolean; issue?: string }> {
  let manifest: CommandManifest;
  try {
    manifest = await readManifest(config.shakaHome);
  } catch (e) {
    return { ok: false, issue: e instanceof Error ? e.message : String(e) };
  }
  const shakaConfig = await loadConfig(config.shakaHome);
  const { commands } = await discoverCommands(config.shakaHome, shakaConfig?.commands?.disabled);

  const isEmpty =
    commands.length === 0 &&
    manifest.global.length === 0 &&
    Object.keys(manifest.scoped).length === 0;
  if (isEmpty) return { ok: true };

  return checkCommandHealth(
    commands,
    manifest,
    ({ command, cwd }) =>
      cwd
        ? join(cwd, ".opencode", "commands", `${command.name}.md`)
        : join(opencodeConfigDir, "commands", `${command.name}.md`),
    async ({ command, cwd }, path) => {
      const commandsDir = cwd
        ? join(cwd, ".opencode", "commands")
        : join(opencodeConfigDir, "commands");
      return isShakaManagedCommand(path, compileOpencodeCommand(command, commandsDir).content);
    },
  );
}
