// SHAKA_GENERATED_EXTENSION v1
//
// Static template — copied verbatim into <piHome>/extensions/shaka.ts during
// `shaka init --pi`. Reads SHAKA_BIN and SHAKA_HOME from the environment at
// runtime (set by Shaka when invoking Pi as a subprocess; falls back to
// `shaka` on PATH and XDG_CONFIG_HOME/shaka (or ~/.config/shaka) for
// direct user invocations — see the SHAKA_HOME resolution below).
//
// DO NOT EDIT this file at the install destination — `shaka reload` will
// overwrite it. Edit the source at `defaults/pi/extension.ts` instead.
//
// Behaviour reference: pi.md "Generated Extension Skeleton" + "Hook
// Invocation Contract". Empirical sources: Exp 44, 45, 48, 49, 50.

import { spawn, spawnSync } from "node:child_process";
import { appendFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

// Minimal local declarations of Pi's ExtensionAPI surface — keeps Shaka free
// of a `@earendil-works/pi-coding-agent` devDependency just to type-check this
// template. The real types are resolved by jiti at the install destination
// (`~/.pi/agent/extensions/shaka.ts`) when Pi loads the extension at runtime.
// Event payload shapes empirically verified in experiments 45 + 48.
interface ExtensionContext {
  sessionManager?: { id?: string; path?: string };
  ui?: { notify?: (message: string, level: "info" | "warning" | "error" | "success") => void };
}
interface BeforeAgentStartEvent {
  prompt?: string;
  systemPrompt?: string;
}
interface ToolCallEvent {
  toolName?: string;
  input?: Record<string, unknown>;
}
interface ToolResultEvent {
  toolName?: string;
  input?: Record<string, unknown>;
  content?: unknown;
  isError?: boolean;
}
type BlockResult = { block: true; reason: string };
type SystemPromptResult = { systemPrompt: string };
type ToolParameter = { type: string; description?: string; enum?: string[] };
/**
 * Tool result shape Pi expects (verified Exp 52 against the bundled grep tool
 * — Pi calls `.filter()` on `result.content` and crashes if `content` is
 * missing). `details` is opaque side-data for richer rendering; we leave it
 * undefined since the model only sees `content`.
 */
type ToolResult = { content: Array<{ type: "text"; text: string }>; details?: undefined };
interface ToolRegistration {
  name: string;
  label: string;
  description: string;
  parameters: { type: "object"; properties: Record<string, ToolParameter>; required?: string[] };
  execute: (toolCallId: string, args: Record<string, unknown>) => Promise<ToolResult>;
}
interface ExtensionAPI {
  on(
    name: "before_agent_start",
    handler: (
      event: BeforeAgentStartEvent,
      ctx: ExtensionContext,
    ) => Promise<SystemPromptResult | undefined>,
  ): void;
  on(
    name: "tool_call",
    handler: (event: ToolCallEvent, ctx: ExtensionContext) => Promise<BlockResult | undefined>,
  ): void;
  on(
    name: "tool_result",
    handler: (event: ToolResultEvent, ctx: ExtensionContext) => Promise<void>,
  ): void;
  on(
    name: "agent_end" | "session_shutdown",
    handler: (event: unknown, ctx: ExtensionContext) => void,
  ): void;
  registerTool(tool: ToolRegistration): void;
}

interface EnvVars {
  SHAKA_HOME?: string;
  XDG_CONFIG_HOME?: string;
  HOME?: string;
  USERPROFILE?: string;
}

const SHAKA_HOME_PLACEHOLDER = "__SHAKA_INSTALLED_HOME__";
const INSTALLED_SHAKA_HOME = "__SHAKA_INSTALLED_HOME__";

// Read per-call (not captured at module load) — same reasoning as
// `isSubagent()` below: keeps integration tests honest when they swap
// SHAKA_BIN between cases, and survives Pi's extension-cache reuse where
// our module is loaded once and reused across many sessions.
function shakaBin(): string {
  return process.env.SHAKA_BIN ?? "shaka";
}
// Mirror src/domain/config.ts:resolveShakaHome — SHAKA_HOME wins, then
// XDG_CONFIG_HOME/shaka, then HOME/USERPROFILE, then os.homedir(). The
// extension can't import from src/ at jiti-load time, so the precedence is
// inlined here.
export function resolveExtensionShakaHome(env: EnvVars = process.env as EnvVars): string {
  if (INSTALLED_SHAKA_HOME !== SHAKA_HOME_PLACEHOLDER) return INSTALLED_SHAKA_HOME;
  if (env.SHAKA_HOME) return env.SHAKA_HOME;
  if (env.XDG_CONFIG_HOME) return join(env.XDG_CONFIG_HOME, "shaka");
  const home = env.HOME || env.USERPROFILE;
  if (home) return join(home, ".config", "shaka");
  return join(homedir(), ".config", "shaka");
}

function currentShakaHome(): string {
  return resolveExtensionShakaHome();
}

function errorLogPath(): string {
  return join(currentShakaHome(), "state", "pi-extension-errors.log");
}

function shakaEnv(): NodeJS.ProcessEnv {
  return { ...process.env, SHAKA_HOME: currentShakaHome() };
}

// Primary recursion guard. Set true when Shaka invokes Pi as inference or as
// a subagent. Read per-handler (not at module load) so the value reflects the
// process env at the time the handler fires — keeps integration tests honest
// (they can mutate env between calls) and survives Pi's extension-cache
// reuse model.
function isSubagent(): boolean {
  return process.env.SHAKA_PI_SUBAGENT === "true";
}

// Pi tool name → Shaka canonical name. Pi has only 4 built-in tools (Exp 48
// verified live; bash subsumes ls/grep/find). Extension-registered tools
// would each need their own normalization entry added here.
const TOOL_NAME_MAP: Record<string, string> = {
  bash: "Bash",
  read: "Read",
  write: "Write",
  edit: "Edit",
};

const SESSION_END_IDLE_MS = 3_000;

interface HookResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

// Synchronous hook for tool.before, prompt.submit, session.start — caller
// reads exitCode/stdout to make a control-flow decision.
//
// Distinguishes a clean non-zero exit (hook ran and returned a status) from
// a true internal failure (binary missing, killed by signal, timed out).
// Internal failures fail CLOSED via exitCode 2 so the security gate isn't
// silently disabled by a misconfigured SHAKA_BIN; hook-emitted exit codes
// pass through verbatim so "exit 1 = advisory" semantics survive.
function runHook(eventName: string, payload: unknown): HookResult {
  const result = spawnSync(shakaBin(), ["hook", eventName], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    env: shakaEnv(),
    timeout: 30_000,
    // Hard kill on timeout — the default SIGTERM is catchable, so a hook
    // that ignores it would block this synchronous call indefinitely on
    // Pi's request thread, defeating the fail-closed security gate.
    killSignal: "SIGKILL",
  });
  if (result.error || result.status === null) {
    const reason =
      result.error?.message ?? `shaka hook ${eventName} terminated without an exit status`;
    return { exitCode: 2, stdout: "", stderr: reason };
  }
  return {
    exitCode: result.status,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

// Fire-and-forget for tool.after and session.end — the response can't change
// the run outcome, so don't block Pi's event loop on every tool result.
//
// Spawn failures (ENOENT, permission, etc.) can surface either way:
// synchronously from `spawn()` on some platforms, or async via the child's
// `error` event. Both belts catch the failure and route it to the sidecar
// log so a misconfigured SHAKA_BIN never destabilizes Pi's extension host
// — Pi swallows handler exceptions silently (Exp 49 H4), so the only
// debugging surface is the log.
function runHookDetached(eventName: string, payload: unknown): void {
  const child = spawn(shakaBin(), ["hook", eventName], {
    detached: true,
    env: shakaEnv(),
    stdio: ["pipe", "ignore", "ignore"],
  });
  child.on("error", (err) => writeSidecarErrorLog(`runHookDetached:${eventName}`, err));
  // The stdin pipe has its own error surface — an early-exiting child can
  // emit EPIPE/ERR_STREAM_DESTROYED here independently of the spawn-level
  // `error` event. Mirrors `runShakaTool`'s stdin guard below.
  child.stdin?.on("error", (err) =>
    writeSidecarErrorLog(`runHookDetached:${eventName}:stdin`, err),
  );
  child.stdin?.write(JSON.stringify(payload));
  child.stdin?.end();
  child.unref();
}

// Pi swallows extension exceptions silently even with --verbose (Exp 49 H4).
// A sidecar log is the only debugging surface for handler failures.
function writeSidecarErrorLog(handlerName: string, err: unknown): void {
  try {
    const logPath = errorLogPath();
    mkdirSync(dirname(logPath), { recursive: true });
    const message =
      err instanceof Error ? `${err.name}: ${err.message}\n${err.stack ?? ""}` : String(err);
    appendFileSync(
      logPath,
      `${JSON.stringify({
        t: Date.now(),
        handler: handlerName,
        sessionEnv: isSubagent() ? "subagent" : "user",
        err: message,
      })}\n`,
    );
  } catch {
    // best-effort — if we can't even log, give up silently
  }
}

/**
 * Catalog of Shaka tools to surface to Pi's model. Schema descriptors mirror
 * `defaults/system/tools/*.ts:inputSchema` exactly so they round-trip
 * without translation. When a new tool ships in `defaults/system/tools/`,
 * add an entry here and `shaka reload` propagates it to Pi.
 *
 * Execution always shells to `shaka tool <name>` — keeps tool defs in one
 * place (the `defaults/system/tools/` directory the MCP server already walks
 * for Claude Code and Codex) and avoids embedding tool source in every
 * provider's generated artifact.
 */
const SHAKA_TOOLS: ToolRegistration[] = [
  {
    name: "memory-search",
    label: "memory-search",
    description:
      "Search past session summaries and learnings for context, decisions, and work history. " +
      "Returns matching sessions and learnings with snippets.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search query (case-insensitive substring match)" },
        category: {
          type: "string",
          description: "Filter learnings by category (correction/preference/pattern/fact)",
        },
        cwd: { type: "string", description: "Filter by working directory (substring match)" },
        type: {
          type: "string",
          enum: ["session", "learning"],
          description: "Filter by result type",
        },
      },
      required: ["query"],
    },
    execute: (_toolCallId, args) => runShakaTool("memory-search", args),
  },
  {
    name: "inference",
    label: "inference",
    description:
      "Run AI inference using available CLI tools (claude, opencode, codex, or pi). " +
      "Useful for tasks requiring a separate AI model call.",
    parameters: {
      type: "object",
      properties: {
        prompt: { type: "string", description: "The user prompt to send to the AI model" },
        systemPrompt: { type: "string", description: "Optional system prompt to set context" },
      },
      required: ["prompt"],
    },
    execute: (_toolCallId, args) => runShakaTool("inference", args),
  },
];

// Live-path budget for `shaka tool <name>` invocations. Generous enough for
// real `inference` calls (which can take tens of seconds), tight enough that
// a hung subprocess never wedges Pi waiting for a tool result that won't
// come. Same shape as `runProcessWithTimeout` in
// src/providers/pi/configurer.ts but inlined here — the extension can't
// import from src/ at jiti-load time.
const TOOL_TIMEOUT_MS = 60_000;

function runShakaTool(name: string, args: Record<string, unknown>): Promise<ToolResult> {
  return new Promise((resolve) => {
    const proc = spawn(shakaBin(), ["tool", name], {
      env: shakaEnv(),
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const finish = (text: string): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ content: [{ type: "text", text }] });
    };
    let killTimer: ReturnType<typeof setTimeout> | undefined;
    const timer = setTimeout(() => {
      // SIGTERM → 500ms grace → SIGKILL. Mirrors runAgentStep, opencode
      // runShakaTool, inference.spawnCLI, configurer.runProcessWithTimeout.
      proc.kill("SIGTERM");
      killTimer = setTimeout(() => proc.kill("SIGKILL"), 500);
      killTimer.unref?.();
      finish(`Error: shaka tool ${name} timed out after ${TOOL_TIMEOUT_MS}ms`);
    }, TOOL_TIMEOUT_MS);
    timer.unref?.();
    proc.stdout?.setEncoding("utf8");
    proc.stderr?.setEncoding("utf8");
    proc.stdout?.on("data", (d) => {
      stdout += d;
    });
    proc.stderr?.on("data", (d) => {
      stderr += d;
    });
    proc.stdin?.on("error", () => {
      // Child may exit before consuming stdin; close/error events still
      // decide the resolved value.
    });
    try {
      proc.stdin?.write(JSON.stringify(args));
      proc.stdin?.end();
    } catch {
      // Pipe closed between spawn and write — finish() will run on close/error.
    }
    // close/error fire only after the child has actually exited — that's
    // the safe moment to drop the SIGKILL backstop. Clearing it inside
    // `finish` would cancel SIGKILL before SIGTERM has a chance to land,
    // and a SIGTERM-trapping child would live forever. Mirrors the
    // configurer.runProcessWithTimeout / opencode runShakaTool pattern.
    proc.on("close", (code) => {
      if (killTimer) clearTimeout(killTimer);
      finish(code === 0 ? stdout : `Error: shaka tool ${name} exited ${code}: ${stderr.trim()}`);
    });
    proc.on("error", (err) => {
      if (killTimer) clearTimeout(killTimer);
      finish(`Error: shaka tool ${name} spawn failed: ${err.message}`);
    });
  });
}

export default function (pi: ExtensionAPI) {
  const sessionStartFired = new Set<string>();
  const sessionEndFired = new Set<string>();
  const sessionEndTimers = new Map<string, ReturnType<typeof setTimeout>>();

  for (const tool of SHAKA_TOOLS) {
    pi.registerTool(tool);
  }

  pi.on("before_agent_start", async (event, ctx) => {
    if (isSubagent()) return;
    try {
      const sid = sessionId(ctx);
      const appends: string[] = [];
      clearTimer(sid);
      sessionEndFired.delete(sid);

      // session.start fires lazily on the first turn — eliminates the
      // queued-append state needed if we ran it in a separate session_start
      // handler. Only mark the session as fired AFTER the hook actually
      // ran (exitCode 2 means runHook failed to spawn the shaka binary —
      // we want the next turn to retry once the binary becomes reachable).
      if (!sessionStartFired.has(sid)) {
        const r = runHook("session.start", { session_id: sid, provider: "pi" });
        if (r.exitCode !== 2) sessionStartFired.add(sid);
        if (r.stdout.trim()) appends.push(r.stdout);
      }

      const r = runHook("prompt.submit", {
        session_id: sid,
        prompt: event.prompt ?? "",
        provider: "pi",
      });
      if (r.stdout.trim()) appends.push(r.stdout);

      if (appends.length > 0) {
        return {
          systemPrompt: `${event.systemPrompt ?? ""}\n\n${appends.join("\n\n")}`,
        };
      }
      return;
    } catch (err) {
      writeSidecarErrorLog("before_agent_start", err);
    }
  });

  pi.on("tool_call", async (event, ctx) => {
    if (isSubagent()) return;
    try {
      const piToolName = event.toolName ?? "";
      const shakaToolName = TOOL_NAME_MAP[piToolName] ?? piToolName;
      const r = runHook("tool.before", {
        session_id: sessionId(ctx),
        tool_name: shakaToolName,
        tool_input: event.input ?? {},
        provider: "pi",
      });
      if (r.exitCode === 2) {
        const reason = r.stderr.trim() || "blocked by Shaka security policy";
        // ctx.ui.notify is a no-op in print mode (Exp 49 H2 rejected) — log
        // to stderr explicitly so headless contexts see the block reason.
        console.error(`[shaka] BLOCKED ${shakaToolName}: ${reason}`);
        ctx.ui?.notify?.(reason, "warning"); // best-effort for TUI
        return { block: true, reason };
      }
      // Fail open for non-block exit codes (e.g., hook crashed). Allow.
      return;
    } catch (err) {
      writeSidecarErrorLog("tool_call", err);
      // Pi treats handler throw as fail-CLOSED (Exp 49 H3) — make the
      // verdict explicit so the cause stays debuggable.
      return {
        block: true,
        reason: `shaka extension internal error (see ${errorLogPath()})`,
      };
    }
  });

  pi.on("tool_result", async (event, ctx) => {
    if (isSubagent()) return;
    try {
      const piToolName = event.toolName ?? "";
      runHookDetached("tool.after", {
        session_id: sessionId(ctx),
        tool_name: TOOL_NAME_MAP[piToolName] ?? piToolName,
        tool_input: event.input ?? {},
        tool_response: event.content ?? null,
        is_error: event.isError ?? false,
        provider: "pi",
      });
    } catch (err) {
      writeSidecarErrorLog("tool_result", err);
    }
  });

  // Session-end debounce: collapse per-turn `agent_end` events into a single
  // session.end firing. `agent_end` fires once per user turn (Exp 50);
  // `session_shutdown` always fires once per process invocation (Exp 45 + 50).
  pi.on("agent_end", (_event, ctx) => {
    if (isSubagent()) return;
    const sid = sessionId(ctx);
    clearTimer(sid);
    sessionEndTimers.set(
      sid,
      setTimeout(() => fireSessionEnd(ctx, sid), SESSION_END_IDLE_MS),
    );
  });

  pi.on("session_shutdown", (_event, ctx) => {
    if (isSubagent()) return;
    const sid = sessionId(ctx);
    clearTimer(sid);
    fireSessionEnd(ctx, sid);
    // Release per-session state so the sets don't grow unbounded across
    // long-lived Pi hosts. Especially important for the `"unknown"`
    // fallback id — without this, the first id-less session would
    // permanently suppress session.start or session.end for later id-less
    // sessions.
    sessionStartFired.delete(sid);
    sessionEndFired.delete(sid);
  });

  function fireSessionEnd(ctx: ExtensionContext, sid: string): void {
    sessionEndTimers.delete(sid);
    if (sessionEndFired.has(sid)) return;
    sessionEndFired.add(sid);
    try {
      runHookDetached("session.end", {
        session_id: sid,
        provider: "pi",
        transcript_path: ctx.sessionManager?.path ?? null,
      });
    } catch (err) {
      writeSidecarErrorLog("session.end", err);
    }
  }

  function clearTimer(sid: string): void {
    const existing = sessionEndTimers.get(sid);
    if (existing) clearTimeout(existing);
    sessionEndTimers.delete(sid);
  }
}

function sessionId(ctx: ExtensionContext): string {
  return ctx.sessionManager?.id ?? "unknown";
}
